package it.belloworld.mercurygram;

import java.text.Normalizer;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Mercurygram: folds text written with decorated Unicode "fonts" down to plain ASCII, so that
 * searching for "Cucina italiana" finds a group actually named
 * "ℂᑌℂℐℕᗅ ℐᝨᗅℒℐᗅℕᗅ".
 *
 * Those alphabets come from two different places:
 *
 * - compatibility variants of the Latin letters (Letterlike Symbols, Mathematical Alphanumeric
 *   Symbols, fullwidth, circled, ...), which NFKD decomposition maps back on its own;
 * - unrelated scripts picked purely because a glyph looks like a Latin letter (Cherokee, Lisu,
 *   Canadian Aboriginal Syllabics, Tagbanwa, ...), which only a lookalike table can map.
 *
 * The output feeds LocaleController.getTranslitString, whose own table covers precomposed Latin
 * characters only and walks the string one UTF-16 unit at a time, so it handles neither case
 * (Mathematical Alphanumerics are not even single UTF-16 units).
 */
public class MgUnicodeFold {

    // Below this codepoint NFKD decomposition is left to the upstream transliteration table, which
    // already owns every precomposed Latin character. The lookalike table below has no such floor:
    // upstream leaves holes even in Latin Extended ("Ɩ", "ŋ"), which is what made a group named
    // "Ɩơ۷ɛ ıʂƖąŋɖ" unsearchable.
    private static final int FOLD_FROM = 0x0250;

    /**
     * Lookalike codepoint followed by its ASCII letter or digit, generated by
     * scripts/gen-unicode-fold.py from the Unicode confusables data (UTS #39,
     * https://www.unicode.org/Public/security/latest/confusables.txt). Re-run it to pick up a
     * newer Unicode release; do not edit the literal by hand.
     *
     * What the table does and does not cover, and why, is documented in that script next to the
     * filters that decide it. The one rule worth repeating here: the upstream table wins wherever
     * both know a codepoint, because the script subtracts its keys.
     */
    // 597 entries, generated by scripts/gen-unicode-fold.py from confusables.txt 17.0.0
    private static final String LOOKALIKE_PAIRS =
            "¢c¥yÐd×xØoĐdĦhŁlŋnŦtƂbƄbƉdƍgƑfƖlƗlƝnƟoƦrƧ2Ʈt"
            + "ƵzƷ3ƻ2Ƽ5ƽsƿpǀlǤgǮ3ǾoȜ3Ȣ8ȤzȾtɄuɆeɈjɎyɑaɣyɩiʱh"
            + "ˠyϨ2Ϭ6ϭo١l٥o٧v۱l۵o۷v߀o०o३3০o৪8৭9੦o੧9੪8૦o૩3୦o"
            + "୨9௦o౦o೦o൦o൭9๐o໐o၀oᎠdᎡrᎢtᎥiᎩyᎪaᎫjᎬeᎳwᎷmᎻhᎽyᎾo"
            + "ᏀgᏂhᏃzᏌuᏎ4ᏏbᏒrᏔwᏕsᏙvᏚsᏞlᏟcᏢpᏦkᏧdᏫoᏮ6ᏲhᏳgᏴbᐯv"
            + "ᑌuᑭpᑯdᑲbᑳbᒍjᒪlᒿ2ᕁxᕼhᕽxᖇrᖯbᖴfᗅaᗞdᗪdᗰmᗷb᙭x᙮xᚷx"
            + "ᛁlᛕkᛖmᝨtᝪo០oᴽ8ᵅaᵑnᵚwᵞyᵧyᵨpᵸhᵻiᵼiᵾuᶢgᶤiᶥiᶦiᶧi"
            + "ᶩlᶯnᶱoᶳsᶸuᶹuᶼzᶿo₡c₩w₫d₭k₮tℏh℮eℽy∣l∤l∨v∪u⊖o⊝o"
            + "⊤t⋁v⋃u⋿e⍡t⍬o⍳i⍴p⍶a⍸i⍺a⏽l╳x⟙t⤫x⤬x⨯x⨰xⱧhⱩkⲂbⲅr"
            + "ⲎhⲐoⲑoⲒlⲓiⲔkⲘmⲚnⲜ3ⲞoⲟoⲢpⲣpⲤcⲥcⲦtⲨyⲩyⲬxⲽwⳄ3Ⳋ9"
            + "ⳋ9Ⳍ3ⳎpⳏpⳐlⳒ6ⳓ6Ⳝ6ⴱoⴸvⴹeⵁoⵏlⵔoⵕqⵝxꓐbꓑpꓒdꓓdꓔtꓖg"
            + "ꓗkꓙjꓚcꓜzꓝfꓟmꓠnꓡlꓢsꓣrꓦvꓧhꓪwꓫxꓬyꓮaꓰeꓲlꓳoꓴuꛟvꛯ2"
            + "ꝀkꝊoꝚ2Ꝫ3Ꝯ9ꞘfꞙfꞟuꞫ3ꞲjꞳxꞴbꟸhꬲeꬵfꬽoꬾoꭇrꭈrꭎuꭒuꭚy"
            + "ꭞlꭟuꭴoꭵiꮁrꮃwꮎoꮓzꮜuꮩvꮪsꮯcꮻo￠c￥y￦w￨l𐆖x𐆗v𐊂b𐊆e𐊇f"
            + "𐊊l𐊐x𐊒o𐊕p𐊖s𐊗t𐊠a𐊡b𐊢c𐊥f𐊫o𐊰m𐊱t𐊲y𐊴x𐋏h𐋵z𐌁b𐌂c𐌉l𐌑m𐌕t"
            + "𐌗x𐌚8𐌠l𐌢x𐐄o𐐕c𐐛l𐐠s𐐬o𐐽c𐑈s𐒴r𐓂o𐓎u𐓒7𐓪o𐓶u𐔓n𐔖o𐔘k𐔜c𐔝v"
            + "𐔥f𐔦l𐔧x𐞅b𐞋d𐞌d𐞓g𐞕h𐞢o𐞨r𐞲y𐞶l𑓅w𑓐o𑜆v𑜊w𑜎w𑜏w𑢠v𑢢f𑢣l𑢤y"
            + "𑢦e𑢩z𑢬9𑢮e𑢯4𑢲l𑢵o𑢸u𑢻5𑢼t𑣀v𑣁s𑣂f𑣃i𑣄z𑣆7𑣈o𑣊3𑣌9𑣕6𑣖9𑣗o"
            + "𑣘u𑣜y𑣠o𑣥z𑣦w𑣩c𑣬x𑣯w𑣲c𖼈v𖼊t𖼖l𖼨l𖼵r𖼺s𖼻3𖽀a𖽂u𖽃y𝚤i𝚨a𝚩b"
            + "𝚬e𝚭z𝚮h𝚯o𝚰l𝚱k𝚳m𝚴n𝚶o𝚸p𝚹o𝚻t𝚼y𝚾x𝛂a𝛄y𝛈n𝛉o𝛊i𝛎v𝛐o𝛒p"
            + "𝛔o𝛖u𝛝o𝛠p𝛢a𝛣b𝛦e𝛧z𝛨h𝛩o𝛪l𝛫k𝛭m𝛮n𝛰o𝛲p𝛳o𝛵t𝛶y𝛸x𝛼a𝛾y"
            + "𝜂n𝜃o𝜄i𝜈v𝜊o𝜌p𝜎o𝜐u𝜗o𝜚p𝜜a𝜝b𝜠e𝜡z𝜢h𝜣o𝜤l𝜥k𝜧m𝜨n𝜪o𝜬p"
            + "𝜭o𝜯t𝜰y𝜲x𝜶a𝜸y𝜼n𝜽o𝜾i𝝂v𝝄o𝝆p𝝈o𝝊u𝝑o𝝔p𝝖a𝝗b𝝚e𝝛z𝝜h𝝝o"
            + "𝝞l𝝟k𝝡m𝝢n𝝤o𝝦p𝝧o𝝩t𝝪y𝝬x𝝰a𝝲y𝝶n𝝷o𝝸i𝝼v𝝾o𝞀p𝞂o𝞄u𝞋o𝞎p"
            + "𝞐a𝞑b𝞔e𝞕z𝞖h𝞗o𝞘l𝞙k𝞛m𝞜n𝞞o𝞠p𝞡o𝞣t𝞤y𝞦x𝞪a𝞬y𝞰n𝞱o𝞲i𝞶v"
            + "𝞸o𝞺p𝞼o𝞾u𝟅o𝟈p𝟊f𞀰a𞀱6𞀳r𞀵e𞀼o𞀾p𞀿c𞁁y𞁃x𞁆w𞁌i𞁍j𞁎o𞁏y𞁐l"
            + "𞁑a𞁒6𞁔r𞁖e𞁜o𞁞c𞁟y𞁡x𞁤w𞁨i𞁩s𞁪u𞁫c𞁭y𞣇l𞣋8𞸀l𞸤o𞹤o𞺀l𞺄o🜈v"
            + "🜔o🝌c🝨t";

    // Memoized per-codepoint results ("" means leave untouched), pre-seeded with the lookalike
    // table. getTranslitString runs per keystroke over every dialog name and over every message
    // indexed for search; without the memoization, every real-script codepoint above FOLD_FROM
    // would pay a Normalizer round trip per call just to conclude it needs no folding.
    private static final Map<Integer, String> FOLD_CACHE = new ConcurrentHashMap<>();

    static {
        for (int i = 0; i < LOOKALIKE_PAIRS.length(); ) {
            final int cp = LOOKALIKE_PAIRS.codePointAt(i);
            i += Character.charCount(cp);
            FOLD_CACHE.put(cp, String.valueOf(LOOKALIKE_PAIRS.charAt(i)));
            i++;
        }
    }

    /**
     * Returns {@code src} with every decorated codepoint replaced by its plain lowercase ASCII
     * equivalent. Plain characters, and characters from scripts we have no mapping for, are
     * returned untouched - case included, so ASCII text comes back identical and the very same
     * instance is returned when nothing needed folding.
     */
    public static String fold(String src) {
        if (src == null) {
            return null;
        }
        StringBuilder dst = null;
        final int len = src.length();
        for (int i = 0; i < len; ) {
            final int cp = src.codePointAt(i);
            final String replacement = replacement(cp);
            if (replacement.isEmpty()) {
                if (dst != null) {
                    dst.appendCodePoint(cp);
                }
            } else {
                if (dst == null) {
                    dst = new StringBuilder(len).append(src, 0, i);
                }
                dst.append(replacement);
            }
            i += Character.charCount(cp);
        }
        return dst == null ? src : dst.toString();
    }

    // ASCII, Cyrillic and the CJK Unified Ideographs are the three biggest bodies of real text the
    // app indexes, and none of those blocks holds a lookalike entry or a compatibility
    // decomposition, so skip even the cache lookup (and its Integer boxing) for them.
    private static boolean maybeDecorated(int cp) {
        return cp >= 0x80 && (cp < 0x400 || cp > 0x52f) && (cp < 0x4e00 || cp > 0x9fff);
    }

    private static String replacement(int cp) {
        if (!maybeDecorated(cp)) {
            return "";
        }
        String r = FOLD_CACHE.get(cp);
        if (r == null) {
            // Only the lookalike table reaches below FOLD_FROM, and it is pre-seeded into the
            // cache, so a miss down there is a codepoint the upstream table owns.
            FOLD_CACHE.put(cp, r = cp < FOLD_FROM ? "" : computeReplacement(cp));
        }
        return r;
    }

    private static String computeReplacement(int cp) {
        final String decomposed =
                Normalizer.normalize(new String(Character.toChars(cp)), Normalizer.Form.NFKD);
        final StringBuilder sb = new StringBuilder(decomposed.length());
        for (int i = 0; i < decomposed.length(); i++) {
            final char c = decomposed.charAt(i);
            // the marks NFKD split off are decoration too, drop them
            if (Character.getType(c) == Character.NON_SPACING_MARK) {
                continue;
            }
            // A non-ASCII base means this is real text, not decoration: Cyrillic "ё"
            // decomposes to "е" (breaking the upstream "ё" -> "yo" transliteration),
            // Hangul syllables decompose to jamo, kana lose their voicing mark. Leave those to
            // the upstream tables, which own everything that is not plain ASCII.
            if (c >= 0x80) {
                return "";
            }
            sb.append(Character.toLowerCase(c));
        }
        return sb.toString();
    }
}
